api:
  config:
    mail-url: ${MAIL_URL}
spring:
  application:
    name: ProjectOne
  datasource:
    username: olvmky@project-one
    password: revature123!
    url: jdbc:postgresql://project-one.postgres.database.azure.com:5432/project-one
    driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          format_sql: true
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8888

jwt:
  secret: token_secret
  expiry: 360000



